### ISSUE TITLE
Add ignoreOverridden support for MissingModifierDefaultValue rule

### ISSUE THREAD

**Issue by Sx1a9z4f** [appKODE/detekt-rules-compose#11]
Since `An overriding function is not allowed to specify default values ​​for its parameters` I would like to be able to disable this rule for overriding functions.

**Comment by dimsuz** [comment]
Nice catch!

Perhaps this should even be done without adding the `ignoreOverridden` config option, i.e. it should always ignore overriding functions.

Or is there some case you see when this will be useful?

**Comment by OverSadBoy** [comment]
I really can't imagine such a situation) So it needs to be permanent.

**Comment by Sx1a9z4f** [comment]
It may still be worth including abstract functions, because they also will not have a default implementation

**Comment by dimsuz** [comment]
Right! Didn't think of that right away, will include them too.

**Comment by BraisGabin** [comment]
Same for `interface`s. I'm getting this error:

> `Abstract Composable functions cannot have parameters with default values`

**Comment by dimsuz** [comment]
Reopening as I have fixed the problem with overrides, but this rule will still report functions in abstract classes/interfaces. Will do a quick patch-release with the fix.
