### ISSUE TITLE
Improve message on `ComposableEventParameterNaming`

### ISSUE THREAD

**Issue by BraisGabin** [appKODE/detekt-rules-compose#2]
I'm getting legit errors like this:

> ``/the/path/QuantityRow.kt:27:5: Invalid event parameter name. Use names like "onClick", "onValueChange" etc [ComposableEventParameterNaming]``

It would be great to know what's the current parameter name from this message. Something like:

> ``Invalid event parameter name `doSomething`. Use names like "onClick", "onValueChange", etc``

If you agree I can open a PR changing it.

**Comment by dimsuz** [comment]
That would be great, thanks!
