### ISSUE TITLE
Fat jar

### ISSUE THREAD

**Issue by alaegin** [appKODE/detekt-rules-compose#22]
Hello!

It would be nice to have a fat-jar to be used with detekt CLI like in [twitter rules repository](https://github.com/twitter/compose-rules/releases)

**Comment by dimsuz** [comment]
Hello!

This is a nice idea, thanks!

**Comment by PatrickVvB** [comment]
Hi everyone!

Do you still have plans for jar? In our case, we don't want to use detekt with gradle.

**Comment by dimsuz** [comment]
Hi, yes, I'll try to look into it soon!

**Comment by dimsuz** [comment]
Fresh [`1.4.0` release](https://github.com/appKODE/detekt-rules-compose/releases/tag/v1.4.0) contains a fat jar with rules!
Please report if there are any issues with it.
