### ISSUE TITLE
Private Composable Previews and UnusedPrivateMember conflict

### ISSUE THREAD

**Issue by BugsBunnyBR** [appKODE/detekt-rules-compose#26]
When I enable `PublicComposablePreview` and set all my previews to `private` this causes `UnusedPrivateMember` to be triggered.
How to avoid that?

**Comment by BraisGabin** [comment]
Like this: https://detekt.dev/docs/introduction/compose/

**Comment by BugsBunnyBR** [comment]
Thank you, maybe we could add a warning in the readme about it?
