### ISSUE TITLE
[MissingModifierDefaultValue] Rules in KMM

### ISSUE THREAD

**Issue by aptech73** [appKODE/detekt-rules-compose#38]
Good afternoon, colleagues.

When using the library with Compose Multiplatform, some rules work incorrectly. I suggest adding support for KMM.

For example, functions marked actual should not have default values:
`Actual function cannot have default argument values, they should be declared in the expected function`

However, linter highlights that modifier has no default value:
`Modifier parameter should have a default value: “modifier = Modifier” [MissingModifierDefaultValue]`

**Comment by dimsuz** [comment]
Indeed, the presence of `actual` should be checked and the error should not be reported!

**Comment by dimsuz** [comment]
Fixed by #39
